#include "country_ids.hh"

uint8_t shiro::geoloc::get_country_id(const std::string &country_code) {
    // Code below was auto generated by a Python script
    if (country_code == "BL") {
        return (uint8_t) country_id::BL;
    } else if (country_code == "AD") {
        return (uint8_t) country_id::AD;
    } else if (country_code == "AF") {
        return (uint8_t) country_id::AF;
    } else if (country_code == "AI") {
        return (uint8_t) country_id::AI;
    } else if (country_code == "AL") {
        return (uint8_t) country_id::AL;
    } else if (country_code == "AM") {
        return (uint8_t) country_id::AM;
    } else if (country_code == "AO") {
        return (uint8_t) country_id::AO;
    } else if (country_code == "AQ") {
        return (uint8_t) country_id::AQ;
    } else if (country_code == "AR") {
        return (uint8_t) country_id::AR;
    } else if (country_code == "AS") {
        return (uint8_t) country_id::AS;
    } else if (country_code == "AT") {
        return (uint8_t) country_id::AT;
    } else if (country_code == "AU") {
        return (uint8_t) country_id::AU;
    } else if (country_code == "AW") {
        return (uint8_t) country_id::AW;
    } else if (country_code == "AZ") {
        return (uint8_t) country_id::AZ;
    } else if (country_code == "BB") {
        return (uint8_t) country_id::BB;
    } else if (country_code == "BD") {
        return (uint8_t) country_id::BD;
    } else if (country_code == "BE") {
        return (uint8_t) country_id::BE;
    } else if (country_code == "BF") {
        return (uint8_t) country_id::BF;
    } else if (country_code == "BG") {
        return (uint8_t) country_id::BG;
    } else if (country_code == "BH") {
        return (uint8_t) country_id::BH;
    } else if (country_code == "BI") {
        return (uint8_t) country_id::BI;
    } else if (country_code == "BJ") {
        return (uint8_t) country_id::BJ;
    } else if (country_code == "BM") {
        return (uint8_t) country_id::BM;
    } else if (country_code == "BO") {
        return (uint8_t) country_id::BO;
    } else if (country_code == "BR") {
        return (uint8_t) country_id::BR;
    } else if (country_code == "BS") {
        return (uint8_t) country_id::BS;
    } else if (country_code == "BT") {
        return (uint8_t) country_id::BT;
    } else if (country_code == "BV") {
        return (uint8_t) country_id::BV;
    } else if (country_code == "BW") {
        return (uint8_t) country_id::BW;
    } else if (country_code == "BY") {
        return (uint8_t) country_id::BY;
    } else if (country_code == "BZ") {
        return (uint8_t) country_id::BZ;
    } else if (country_code == "CA") {
        return (uint8_t) country_id::CA;
    } else if (country_code == "CC") {
        return (uint8_t) country_id::CC;
    } else if (country_code == "CF") {
        return (uint8_t) country_id::CF;
    } else if (country_code == "CH") {
        return (uint8_t) country_id::CH;
    } else if (country_code == "CK") {
        return (uint8_t) country_id::CK;
    } else if (country_code == "CL") {
        return (uint8_t) country_id::CL;
    } else if (country_code == "CM") {
        return (uint8_t) country_id::CM;
    } else if (country_code == "CN") {
        return (uint8_t) country_id::CN;
    } else if (country_code == "CO") {
        return (uint8_t) country_id::CO;
    } else if (country_code == "CR") {
        return (uint8_t) country_id::CR;
    } else if (country_code == "CU") {
        return (uint8_t) country_id::CU;
    } else if (country_code == "CV") {
        return (uint8_t) country_id::CV;
    } else if (country_code == "CX") {
        return (uint8_t) country_id::CX;
    } else if (country_code == "CY") {
        return (uint8_t) country_id::CY;
    } else if (country_code == "CZ") {
        return (uint8_t) country_id::CZ;
    } else if (country_code == "DE") {
        return (uint8_t) country_id::DE;
    } else if (country_code == "DJ") {
        return (uint8_t) country_id::DJ;
    } else if (country_code == "DK") {
        return (uint8_t) country_id::DK;
    } else if (country_code == "DM") {
        return (uint8_t) country_id::DM;
    } else if (country_code == "DO") {
        return (uint8_t) country_id::DO;
    } else if (country_code == "DZ") {
        return (uint8_t) country_id::DZ;
    } else if (country_code == "EC") {
        return (uint8_t) country_id::EC;
    } else if (country_code == "EE") {
        return (uint8_t) country_id::EE;
    } else if (country_code == "EG") {
        return (uint8_t) country_id::EG;
    } else if (country_code == "EH") {
        return (uint8_t) country_id::EH;
    } else if (country_code == "ER") {
        return (uint8_t) country_id::ER;
    } else if (country_code == "ES") {
        return (uint8_t) country_id::ES;
    } else if (country_code == "ET") {
        return (uint8_t) country_id::ET;
    } else if (country_code == "FI") {
        return (uint8_t) country_id::FI;
    } else if (country_code == "FJ") {
        return (uint8_t) country_id::FJ;
    } else if (country_code == "FK") {
        return (uint8_t) country_id::FK;
    } else if (country_code == "FO") {
        return (uint8_t) country_id::FO;
    } else if (country_code == "FR") {
        return (uint8_t) country_id::FR;
    } else if (country_code == "GA") {
        return (uint8_t) country_id::GA;
    } else if (country_code == "GB") {
        return (uint8_t) country_id::GB;
    } else if (country_code == "GD") {
        return (uint8_t) country_id::GD;
    } else if (country_code == "GE") {
        return (uint8_t) country_id::GE;
    } else if (country_code == "GF") {
        return (uint8_t) country_id::GF;
    } else if (country_code == "GH") {
        return (uint8_t) country_id::GH;
    } else if (country_code == "GI") {
        return (uint8_t) country_id::GI;
    } else if (country_code == "GL") {
        return (uint8_t) country_id::GL;
    } else if (country_code == "GM") {
        return (uint8_t) country_id::GM;
    } else if (country_code == "GN") {
        return (uint8_t) country_id::GN;
    } else if (country_code == "GP") {
        return (uint8_t) country_id::GP;
    } else if (country_code == "GQ") {
        return (uint8_t) country_id::GQ;
    } else if (country_code == "GR") {
        return (uint8_t) country_id::GR;
    } else if (country_code == "GT") {
        return (uint8_t) country_id::GT;
    } else if (country_code == "GU") {
        return (uint8_t) country_id::GU;
    } else if (country_code == "GW") {
        return (uint8_t) country_id::GW;
    } else if (country_code == "GY") {
        return (uint8_t) country_id::GY;
    } else if (country_code == "HK") {
        return (uint8_t) country_id::HK;
    } else if (country_code == "HN") {
        return (uint8_t) country_id::HN;
    } else if (country_code == "HR") {
        return (uint8_t) country_id::HR;
    } else if (country_code == "HT") {
        return (uint8_t) country_id::HT;
    } else if (country_code == "HU") {
        return (uint8_t) country_id::HU;
    } else if (country_code == "ID") {
        return (uint8_t) country_id::ID;
    } else if (country_code == "IE") {
        return (uint8_t) country_id::IE;
    } else if (country_code == "IL") {
        return (uint8_t) country_id::IL;
    } else if (country_code == "IN") {
        return (uint8_t) country_id::IN;
    } else if (country_code == "IO") {
        return (uint8_t) country_id::IO;
    } else if (country_code == "IQ") {
        return (uint8_t) country_id::IQ;
    } else if (country_code == "IS") {
        return (uint8_t) country_id::IS;
    } else if (country_code == "IT") {
        return (uint8_t) country_id::IT;
    } else if (country_code == "JM") {
        return (uint8_t) country_id::JM;
    } else if (country_code == "JO") {
        return (uint8_t) country_id::JO;
    } else if (country_code == "JP") {
        return (uint8_t) country_id::JP;
    } else if (country_code == "KE") {
        return (uint8_t) country_id::KE;
    } else if (country_code == "KG") {
        return (uint8_t) country_id::KG;
    } else if (country_code == "KH") {
        return (uint8_t) country_id::KH;
    } else if (country_code == "KI") {
        return (uint8_t) country_id::KI;
    } else if (country_code == "KM") {
        return (uint8_t) country_id::KM;
    } else if (country_code == "KW") {
        return (uint8_t) country_id::KW;
    } else if (country_code == "KY") {
        return (uint8_t) country_id::KY;
    } else if (country_code == "KZ") {
        return (uint8_t) country_id::KZ;
    } else if (country_code == "LB") {
        return (uint8_t) country_id::LB;
    } else if (country_code == "LI") {
        return (uint8_t) country_id::LI;
    } else if (country_code == "LK") {
        return (uint8_t) country_id::LK;
    } else if (country_code == "LR") {
        return (uint8_t) country_id::LR;
    } else if (country_code == "LS") {
        return (uint8_t) country_id::LS;
    } else if (country_code == "LT") {
        return (uint8_t) country_id::LT;
    } else if (country_code == "LU") {
        return (uint8_t) country_id::LU;
    } else if (country_code == "LV") {
        return (uint8_t) country_id::LV;
    } else if (country_code == "MA") {
        return (uint8_t) country_id::MA;
    } else if (country_code == "MC") {
        return (uint8_t) country_id::MC;
    } else if (country_code == "MG") {
        return (uint8_t) country_id::MG;
    } else if (country_code == "MH") {
        return (uint8_t) country_id::MH;
    } else if (country_code == "ML") {
        return (uint8_t) country_id::ML;
    } else if (country_code == "MM") {
        return (uint8_t) country_id::MM;
    } else if (country_code == "MN") {
        return (uint8_t) country_id::MN;
    } else if (country_code == "MP") {
        return (uint8_t) country_id::MP;
    } else if (country_code == "MQ") {
        return (uint8_t) country_id::MQ;
    } else if (country_code == "MR") {
        return (uint8_t) country_id::MR;
    } else if (country_code == "MS") {
        return (uint8_t) country_id::MS;
    } else if (country_code == "MT") {
        return (uint8_t) country_id::MT;
    } else if (country_code == "MU") {
        return (uint8_t) country_id::MU;
    } else if (country_code == "MV") {
        return (uint8_t) country_id::MV;
    } else if (country_code == "MW") {
        return (uint8_t) country_id::MW;
    } else if (country_code == "MX") {
        return (uint8_t) country_id::MX;
    } else if (country_code == "MY") {
        return (uint8_t) country_id::MY;
    } else if (country_code == "MZ") {
        return (uint8_t) country_id::MZ;
    } else if (country_code == "NA") {
        return (uint8_t) country_id::NA;
    } else if (country_code == "NC") {
        return (uint8_t) country_id::NC;
    } else if (country_code == "NE") {
        return (uint8_t) country_id::NE;
    } else if (country_code == "NF") {
        return (uint8_t) country_id::NF;
    } else if (country_code == "NG") {
        return (uint8_t) country_id::NG;
    } else if (country_code == "NI") {
        return (uint8_t) country_id::NI;
    } else if (country_code == "NL") {
        return (uint8_t) country_id::NL;
    } else if (country_code == "NO") {
        return (uint8_t) country_id::NO;
    } else if (country_code == "NP") {
        return (uint8_t) country_id::NP;
    } else if (country_code == "NR") {
        return (uint8_t) country_id::NR;
    } else if (country_code == "NU") {
        return (uint8_t) country_id::NU;
    } else if (country_code == "NZ") {
        return (uint8_t) country_id::NZ;
    } else if (country_code == "OM") {
        return (uint8_t) country_id::OM;
    } else if (country_code == "PA") {
        return (uint8_t) country_id::PA;
    } else if (country_code == "PE") {
        return (uint8_t) country_id::PE;
    } else if (country_code == "PF") {
        return (uint8_t) country_id::PF;
    } else if (country_code == "PG") {
        return (uint8_t) country_id::PG;
    } else if (country_code == "PH") {
        return (uint8_t) country_id::PH;
    } else if (country_code == "PK") {
        return (uint8_t) country_id::PK;
    } else if (country_code == "PL") {
        return (uint8_t) country_id::PL;
    } else if (country_code == "PN") {
        return (uint8_t) country_id::PN;
    } else if (country_code == "PR") {
        return (uint8_t) country_id::PR;
    } else if (country_code == "PS") {
        return (uint8_t) country_id::PS;
    } else if (country_code == "PT") {
        return (uint8_t) country_id::PT;
    } else if (country_code == "PW") {
        return (uint8_t) country_id::PW;
    } else if (country_code == "PY") {
        return (uint8_t) country_id::PY;
    } else if (country_code == "QA") {
        return (uint8_t) country_id::QA;
    } else if (country_code == "RE") {
        return (uint8_t) country_id::RE;
    } else if (country_code == "RO") {
        return (uint8_t) country_id::RO;
    } else if (country_code == "RW") {
        return (uint8_t) country_id::RW;
    } else if (country_code == "SA") {
        return (uint8_t) country_id::SA;
    } else if (country_code == "SB") {
        return (uint8_t) country_id::SB;
    } else if (country_code == "SC") {
        return (uint8_t) country_id::SC;
    } else if (country_code == "SD") {
        return (uint8_t) country_id::SD;
    } else if (country_code == "SE") {
        return (uint8_t) country_id::SE;
    } else if (country_code == "SG") {
        return (uint8_t) country_id::SG;
    } else if (country_code == "SI") {
        return (uint8_t) country_id::SI;
    } else if (country_code == "SJ") {
        return (uint8_t) country_id::SJ;
    } else if (country_code == "SK") {
        return (uint8_t) country_id::SK;
    } else if (country_code == "SL") {
        return (uint8_t) country_id::SL;
    } else if (country_code == "SM") {
        return (uint8_t) country_id::SM;
    } else if (country_code == "SN") {
        return (uint8_t) country_id::SN;
    } else if (country_code == "SO") {
        return (uint8_t) country_id::SO;
    } else if (country_code == "SR") {
        return (uint8_t) country_id::SR;
    } else if (country_code == "ST") {
        return (uint8_t) country_id::ST;
    } else if (country_code == "SV") {
        return (uint8_t) country_id::SV;
    } else if (country_code == "SZ") {
        return (uint8_t) country_id::SZ;
    } else if (country_code == "TC") {
        return (uint8_t) country_id::TC;
    } else if (country_code == "TD") {
        return (uint8_t) country_id::TD;
    } else if (country_code == "TF") {
        return (uint8_t) country_id::TF;
    } else if (country_code == "TG") {
        return (uint8_t) country_id::TG;
    } else if (country_code == "TH") {
        return (uint8_t) country_id::TH;
    } else if (country_code == "TJ") {
        return (uint8_t) country_id::TJ;
    } else if (country_code == "TK") {
        return (uint8_t) country_id::TK;
    } else if (country_code == "TM") {
        return (uint8_t) country_id::TM;
    } else if (country_code == "TN") {
        return (uint8_t) country_id::TN;
    } else if (country_code == "TO") {
        return (uint8_t) country_id::TO;
    } else if (country_code == "TR") {
        return (uint8_t) country_id::TR;
    } else if (country_code == "TT") {
        return (uint8_t) country_id::TT;
    } else if (country_code == "TV") {
        return (uint8_t) country_id::TV;
    } else if (country_code == "TW") {
        return (uint8_t) country_id::TW;
    } else if (country_code == "TZ") {
        return (uint8_t) country_id::TZ;
    } else if (country_code == "UA") {
        return (uint8_t) country_id::UA;
    } else if (country_code == "UG") {
        return (uint8_t) country_id::UG;
    } else if (country_code == "US") {
        return (uint8_t) country_id::US;
    } else if (country_code == "UY") {
        return (uint8_t) country_id::UY;
    } else if (country_code == "UZ") {
        return (uint8_t) country_id::UZ;
    } else if (country_code == "VE") {
        return (uint8_t) country_id::VE;
    } else if (country_code == "VN") {
        return (uint8_t) country_id::VN;
    } else if (country_code == "VU") {
        return (uint8_t) country_id::VU;
    } else if (country_code == "WF") {
        return (uint8_t) country_id::WF;
    } else if (country_code == "WS") {
        return (uint8_t) country_id::WS;
    } else if (country_code == "YE") {
        return (uint8_t) country_id::YE;
    } else if (country_code == "YT") {
        return (uint8_t) country_id::YT;
    } else if (country_code == "RS") {
        return (uint8_t) country_id::RS;
    } else if (country_code == "ZA") {
        return (uint8_t) country_id::ZA;
    } else if (country_code == "ZM") {
        return (uint8_t) country_id::ZM;
    } else if (country_code == "ME") {
        return (uint8_t) country_id::ME;
    } else if (country_code == "ZW") {
        return (uint8_t) country_id::ZW;
    } else if (country_code == "AX") {
        return (uint8_t) country_id::AX;
    } else if (country_code == "GG") {
        return (uint8_t) country_id::GG;
    } else if (country_code == "IM") {
        return (uint8_t) country_id::IM;
    } else if (country_code == "JE") {
        return (uint8_t) country_id::JE;
    } else if (country_code == "MF") {
        return (uint8_t) country_id::MF;
    }

    return (uint8_t) country_id::JP;  // Default to Japan because we're weebs ¯\_(ツ)_/¯
}
